### ISSUE TITLE
pyk exception thrown in proof

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/kontrol#122]
While testing a fix for #120 , this error came up 
```sh
  File "/nix/store/819rynl5fdc53p8r6j727m3n37qd311f-python3.10-pyk-0.1.461/lib/python3.10/site-packages/pyk/kast/pretty.py", line 145, in _print_kinner
    return self._print_kapply(kast)                                                                                                     
  File "/nix/store/819rynl5fdc53p8r6j727m3n37qd311f-python3.10-pyk-0.1.461/lib/python3.10/site-packages/pyk/kast/pretty.py", line 176, in _print_kapply
    return unparser(*unparsed_args)                                                                                                     
  File "/nix/store/819rynl5fdc53p8r6j727m3n37qd311f-python3.10-pyk-0.1.461/lib/python3.10/site-packages/pyk/kast/pretty.py", line 402, in <lambda>
    return lambda *args: '( ' + printer(*args) + ' )'                                                                                   
TypeError: KEVM._kevm_patch_symbol_table.<locals>.<lambda>() missing 1 required positional argument: 'a2'  
```

I added a `try` block to catch the value that is causing the exception in the `_print_kapply` from the `pyk.kast.pretty` module. And looks like the term that is causing the exception is :
```python
KApply(label=KLabel(name='_AccountCellMap_', params=()), args=(KToken(token='...', sort=KSort(name='K')),)) 
 ['...']
```

In kevm-pyk, the symbol_table for `_AccountCellMap_` is 
```python
symbol_table['_AccountCellMap_'] = paren(lambda a1, a2: a1 + '\n' + a2)
```

**Comment by tothtamas28** [comment]
Plan for handling this issue:

1. Confirm that this is indeed the lambda that raises the exception. (E.g. rename `a2`, see if the exception text changes accordingly.)
2. Figure out where the term comes from.
3. Determine whether the term is ill-formed, or the lambda is not flexible enough.
4. Figure out what caused the regression.

**Comment by ehildenb** [comment]
Is this bug manifesting at `show` time, or at `prove` time? I wasn't able to reproduce it at `prove` time.

**Comment by anvacaru** [comment]
I was able to reproduce this on CI on this PR. https://github.com/runtimeverification/kontrol/actions/runs/6637762084/job/18032962167?pr=126#step:6:1051

**Comment by anvacaru** [comment]
I ran the tests that throw the error without changing the prank rules from https://github.com/runtimeverification/evm-semantics/pull/2130. The proofs are failing as expected.

**Comment by ehildenb** [comment]
Here is how I debugged this issue:

- I checked out the local copy of `kontrol` at branch `anvacaru/test-prank`
- I checked out a local copy of `kevm` in directory `/home/dev/src/evm-semantics` at branch `anvacaru/prank-create`
- I checked out a local copy of `pyk` in directory `/home/dev/src/pyk` at branch `v0.1.461` (the version KEVM is pinned to in that commit).
- I installed the correct version of K that `kontrol` uses at `deps/k_release`, version `6.0.133`, with `kup install k.openssl.procps --version v6.0.133`.
- I pointed `kontrol` at my local checkout of KEVM with the following change:

```
diff --git a/pyproject.toml b/pyproject.toml
index 797baf2..305d8cb 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -15,7 +15,8 @@ kontrol = "kontrol.__main__:main"
 
 [tool.poetry.dependencies]
 python = "^3.10"
-kevm-pyk = { git = "https://github.com/runtimeverification/evm-semantics.git", branch = "anvacaru/prank-create", subdirectory = "kevm-pyk" }
+# kevm-pyk = { git = "https://github.com/runtimeverification/evm-semantics.git", branch = "anvacaru/prank-create", subdirectory = "kevm-pyk" }
+kevm-pyk = { path = "/home/dev/src/evm-semantics/kevm-pyk", develop = true }
 
 [tool.poetry.group.dev.dependencies]
 autoflake = "*"
```

- I pointed KEVM at my local checkout of pyk with the following change:

```
diff --git a/kevm-pyk/pyproject.toml b/kevm-pyk/pyproject.toml
index 7cb32aaa6..c912c6a22 100644
--- a/kevm-pyk/pyproject.toml
+++ b/kevm-pyk/pyproject.toml
@@ -17,7 +17,8 @@ packages = [
 [tool.poetry.dependencies]
 python = "^3.10"
 pathos = "*"
-pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="v0.1.461" }
+# pyk = { git = "https://github.com/runtimeverification/pyk.git", tag="v0.1.461" }
+pyk = { path = "/home/dev/src/pyk", develop = true }
 tomlkit = "^0.11.6"
 xdg-base-dirs = "^6.0.0"
 
```

- I ran the test in Kontrol that was failing, and looked at the stack trace:

```
"""
Traceback (most recent call last):
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/home/dev/src/kontrol/src/kontrol/prove.py", line 223, in init_and_run_proof
    failure_log = print_failure_info(proof, kcfg_explore, options.counterexample_info)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/kevm_pyk/utils.py", line 201, in print_failure_info
    _, reason = kcfg_explore.implication_failure_reason(node_cterm, target_cterm)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 242, in implication_failure_reason
    failing_cells_str = '\n'.join(
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 243, in <genexpr>
    f'{cell}: {self.kprint.pretty_print(minimize_term(rew))}' for cell, rew in failing_cells
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/ktool/kprint.py", line 298, in pretty_print
    ).print(kast)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 94, in print
    return self._print_kinner(kast)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 145, in _print_kinner
    return self._print_kapply(kast)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 170, in _print_kapply
    unparsed_args = [self._print_kinner(arg) for arg in args]
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 170, in <listcomp>
    unparsed_args = [self._print_kinner(arg) for arg in args]
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 145, in _print_kinner
    return self._print_kapply(kast)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 170, in _print_kapply
    unparsed_args = [self._print_kinner(arg) for arg in args]
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 170, in <listcomp>
    unparsed_args = [self._print_kinner(arg) for arg in args]
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 145, in _print_kinner
    return self._print_kapply(kast)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 170, in _print_kapply
    unparsed_args = [self._print_kinner(arg) for arg in args]
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 170, in <listcomp>
    unparsed_args = [self._print_kinner(arg) for arg in args]
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 145, in _print_kinner
    return self._print_kapply(kast)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 176, in _print_kapply
    return unparser(*unparsed_args)
  File "/home/dev/.cache/pypoetry/virtualenvs/kontrol-yevTO0r7-py3.10/lib/python3.10/site-packages/pyk/kast/pretty.py", line 402, in <lambda>
    return lambda *args: '( ' + printer(*args) + ' )'
TypeError: KEVM._kevm_patch_symbol_table.<locals>.<lambda>() missing 1 required positional argument: 'a2'
"""
```

- I saw that it was calling `implication_failure_reason`, which is here: https://github.com/runtimeverification/pyk/blob/97853d2380703f7b3234fcc826cbb7b896c0f717/src/pyk/kcfg/explore.py#L187.
- I noticed that it's doing `no_cell_rewrite_to_dots`, which would potentially cause a `...` to be passed into the pretty-printer when it shouldn't be. So I commented out that line on my local checkout of pyk: https://github.com/runtimeverification/pyk/blob/97853d2380703f7b3234fcc826cbb7b896c0f717/src/pyk/kcfg/explore.py#L239
- This caused it to not crash anymore.

**Comment by ehildenb** [comment]
Here is a ptach to `pyk` that seems to fix this issue:

```
diff --git a/src/pyk/kcfg/explore.py b/src/pyk/kcfg/explore.py
index b8568fb7..46761b7a 100644
--- a/src/pyk/kcfg/explore.py
+++ b/src/pyk/kcfg/explore.py
@@ -8,7 +8,6 @@ from typing import TYPE_CHECKING, final
 from ..cterm import CSubst, CTerm
 from ..kast.inner import KApply, KLabel, KRewrite, KVariable, Subst
 from ..kast.manip import (
-    abstract_term_safely,
     bottom_up,
     extract_lhs,
     extract_rhs,
@@ -17,13 +16,15 @@ from ..kast.manip import (
     minimize_term,
     ml_pred_to_bool,
     push_down_rewrites,
+    sort_ac_collections,
+    split_config_from,
 )
 from ..kast.outer import KRule
 from ..konvert import krule_to_kore
 from ..kore.rpc import SatResult, StopReason, UnknownResult, UnsatResult
 from ..kore.syntax import Import, Module
 from ..prelude import k
-from ..prelude.k import GENERATED_TOP_CELL
+from ..prelude.k import DOTS, GENERATED_TOP_CELL
 from ..prelude.kbool import notBool
 from ..prelude.ml import is_top, mlAnd, mlEquals, mlEqualsFalse, mlEqualsTrue, mlImplies, mlNot, mlTop
 from ..utils import shorten_hashes, single
@@ -191,10 +192,15 @@ class KCFGExplore:
                     lhs = extract_lhs(_term)
                     rhs = extract_rhs(_term)
                     if lhs == rhs:
-                        return KApply(_term.label, [abstract_term_safely(lhs, base_name=_term.label.name)])
+                        return KApply(_term.label, [DOTS])
                 return _term
 
-            return bottom_up(_no_cell_rewrite_to_dots, term)
+            config, _subst = split_config_from(term)
+            subst = Subst(
+                {cell_name: _no_cell_rewrite_to_dots(cell_contents) for cell_name, cell_contents in _subst.items()}
+            )
+
+            return subst(config)
 
         def _is_cell_subst(csubst: KInner) -> bool:
             if type(csubst) is KApply and csubst.label.name == '_==K_':
@@ -227,8 +233,8 @@ class KCFGExplore:
             failing_cells = []
             curr_cell_match = Subst({})
             for cell in antecedent.cells:
-                antecedent_cell = antecedent.cell(cell)
-                consequent_cell = consequent.cell(cell)
+                antecedent_cell = sort_ac_collections(antecedent.cell(cell))
+                consequent_cell = sort_ac_collections(consequent.cell(cell))
                 cell_match = consequent_cell.match(antecedent_cell)
                 if cell_match is not None:
                     _curr_cell_match = curr_cell_match.union(cell_match)
```

**Comment by palinatolmach** [comment]
@anvacaru @yale-vinson an external auditor who's trying to use Kontrol in his work just ran into this issue in his proof, and I found a message from Juan saying he's also seen this error from two months ago. Do you think we can bump the priority for this issue to get it addressed next week?
