### ISSUE TITLE
Error when performing kontrol build on the example file:

### ISSUE THREAD

**Issue by scab24** [runtimeverification/kontrol#259]
# Error

## File

- https://docs.runtimeverification.com/kontrol/guides/kevm-foundry-integration-example

```js
rm -r out && kontrol build
WARNING 2023-12-26 13:52:56,110 kontrol.__main__ - Ignoring command-line option: -O0
WARNING 2023-12-26 13:52:56,110 kontrol.__main__ - Ignoring command-line option: -O1
WARNING 2023-12-26 13:52:56,110 kontrol.__main__ - Ignoring command-line option: -O2
WARNING 2023-12-26 13:52:56,110 kontrol.__main__ - Ignoring command-line option: -O3
Syntax error at /Users/secoalba/Documents/PROGRAMACIÓN/BLOCKCHAIN_DEV/SOLIDITY/SECURITY/TOOLS/FORMAL_VERIFICATION/KONTROL/kontrolexample/out/kompiled/llvm-library/definition.kore:112265.1-584: Expected: [import, sort, hooked-sort, symbol, hooked-symbol, alias, axiom, claim] Actual: <identifier>
[Warning] Compiler: Non exhaustive match detected:
`#lenOfHead(_)_EVM-ABI_Int_TypedArg`(`abi_type_tuple`(_))
	Source(/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kproj/evm-semantics/abi.md)
	Location(291,20,291,61)
	291 |	    syntax Int ::= #lenOfHead ( TypedArg ) [function, total]
	    .	                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Warning] Compiler: Non exhaustive match detected:
`#isStaticType(_)_EVM-ABI_Bool_TypedArg`(`abi_type_tuple`(_))
	Source(/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kproj/evm-semantics/abi.md)
	Location(402,21,402,65)
	402 |	    syntax Bool ::= #isStaticType ( TypedArg ) [function, total]
	    .	                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Warning] Compiler: Non exhaustive match detected:
`_<Gas__GAS-SYNTAX_Bool_Gas_Gas`(infGas(_),_)
	Source(/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kproj/evm-semantics/gas.md)
	Location(23,21,23,54)
	23 |	    syntax Bool ::= Gas  "<Gas" Gas [function, total]
	   .	                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Warning] Compiler: Non exhaustive match detected:
`_<=Gas__GAS-SYNTAX_Bool_Gas_Gas`(infGas(_),infGas(_))
	Source(/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kproj/evm-semantics/gas.md)
	Location(24,21,24,54)
	24 |	                  | Gas "<=Gas" Gas [function, total]
	   .	                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Error] Critical: llvm-kompile returned nonzero exit code: 255
Examine output to see errors.
[Warning] Compiler: Could not find main syntax module with name
FOUNDRY-CONTRACTS in definition.  Use --syntax-module to specify one. Using
FOUNDRY-MAIN as default.
[Warning] Compiler: Could not find main syntax module with name
FOUNDRY-CONTRACTS in definition.  Use --syntax-module to specify one. Using
FOUNDRY-MAIN as default.

kompile stdout:


kompile stderr:
None

kompile returncode:
113
Traceback (most recent call last):
  File "/nix/store/k1fa1zbym97lxs6zrnckhiq6dmazpkdq-python3.10-pyk-0.1.564/lib/python3.10/site-packages/pyk/ktool/kompile.py", line 156, in __call__
    proc_res = run_process(args, logger=_LOGGER, cwd=cwd, check=check)
  File "/nix/store/k1fa1zbym97lxs6zrnckhiq6dmazpkdq-python3.10-pyk-0.1.564/lib/python3.10/site-packages/pyk/utils.py", line 421, in run_process
    res.check_returncode()
  File "/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '('kompile', 'out/kompiled/foundry.k', '--main-module', 'FOUNDRY-MAIN', '--syntax-module', 'FOUNDRY-CONTRACTS', '-I', '/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kproj/evm-semantics', '-I', '/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kproj/plugin', '-I', '/nix/store/rizwwdn12yyj2da6pcnmh1c49f215ml8-python3.10-kontrol-0.1.103/lib/python3.10/site-packages/kontrol/kdist', '--md-selector', 'k & ! symbolic', '--hook-namespaces', 'JSON KRYPTO', '--emit-json', '--backend', 'llvm', '--llvm-kompile-type', 'c', '-ccopt', '-std=c++17', '-ccopt', '-lssl', '-ccopt', '-lcrypto', '-ccopt', '/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/libff/lib/libff.a', '-ccopt', '-I/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/libff/include', '-ccopt', '/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/libcryptopp/lib/libcryptopp.a', '-ccopt', '-I/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/libcryptopp/include', '-ccopt', '/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/libsecp256k1/lib/libsecp256k1.a', '-ccopt', '-I/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/libsecp256k1/include', '-ccopt', '/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/plugin-c/plugin_util.cpp', '-ccopt', '/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/plugin-c/crypto.cpp', '-ccopt', '/nix/store/c2xsc6r7wgn5rh6lak5fhmbxfl96yg2v-kontrol-81217f873d73ee0be9632a0c88d12aa172d9e642/evm-semantics/plugin/plugin-c/blake2.cpp', '-ccopt', '-I/nix/store/gmzqxwang9qb2xb32fg8zlb4x9f6rjmm-procps-1003.1-2008/include', '-ccopt', '-L/nix/store/gmzqxwang9qb2xb32fg8zlb4x9f6rjmm-procps-1003.1-2008/lib', '-ccopt', '-I/nix/store/8l74iwxb06maz26zab30czar2ajqh5q5-openssl-3.0.10-dev/include', '-ccopt', '-L/nix/store/b5k0k7blsfwlxqf929mayv3grxnn64lg-openssl-3.0.10/lib', '--output-definition', 'out/kompiled/llvm-library')' returned non-zero exit status 113.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/rizwwdn12yyj2da6pcnmh1c49f215ml8-python3.10-kontrol-0.1.103/bin/.kontrol-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/rizwwdn12yyj2da6pcnmh1c49f215ml8-python3.10-kontrol-0.1.103/lib/python3.10/site-packages/kontrol/__main__.py", line 88, in main
    execute(**vars(args))
  File "/nix/store/rizwwdn12yyj2da6pcnmh1c49f215ml8-python3.10-kontrol-0.1.103/lib/python3.10/site-packages/kontrol/__main__.py", line 191, in exec_build
    foundry_kompile(
  File "/nix/store/rizwwdn12yyj2da6pcnmh1c49f215ml8-python3.10-kontrol-0.1.103/lib/python3.10/site-packages/kontrol/kompile.py", line 139, in foundry_kompile
    kevm_kompile(
  File "/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kompile.py", line 69, in kevm_kompile
    return run_kompile(
  File "/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kompile.py", line 191, in run_kompile
    [future.result() for future in futures]
  File "/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kompile.py", line 191, in <listcomp>
    [future.result() for future in futures]
  File "/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/k7nyq3rbi44hjbs3gyzgaz41ndff03k5-python3.10-kevm-pyk-1.0.406/lib/python3.10/site-packages/kevm_pyk/kompile.py", line 181, in _kompile_llvm
    kompile_llvm(output_dir=llvm_library, debug=debug, verbose=verbose)
  File "/nix/store/k1fa1zbym97lxs6zrnckhiq6dmazpkdq-python3.10-pyk-0.1.564/lib/python3.10/site-packages/pyk/ktool/kompile.py", line 158, in __call__
    raise RuntimeError(
RuntimeError: ('Command kompile exited with code 113 for: out/kompiled/foundry.k', '', None, 113)
```

# Device specifications:

- MAC:
Apple M1 Pro
16 GB
14.2.1

- Kontrol version: 0.1.103

- llvm-gcc --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

- Python 3.11.6

- xcode-select version 2405.

- nix --version
nix (Nix) 2.18.1

<img width="654" alt="image" src="https://github.com/runtimeverification/kontrol/assets/94926493/18b34da3-bf35-477c-a562-3734399c441f">

<img width="666" alt="image" src="https://github.com/runtimeverification/kontrol/assets/94926493/60897c59-0b9a-4f6f-aa43-b977e68f8468">

<img width="642" alt="image" src="https://github.com/runtimeverification/kontrol/assets/94926493/8a8c79fa-7707-4cdd-989a-2641a5547bf8">

<img width="799" alt="image" src="https://github.com/runtimeverification/kontrol/assets/94926493/20109076-1c69-4f8a-9580-e88ddce4ea1b">

**Comment by anvacaru** [comment]
@scab24 thank you for submitting this issue! Unfortunately, I was not able to replicate your issue. Could you upload the `kontrolexample/out/kompiled/llvm-library/definition.kore` file?

**Comment by scab24** [comment]
## I'm sharing line 112265 and its continuation with you.


```js
// rule `method_lib%forge-std%lib%ds-test%src%DSTest`(`contract_lib%forge-std%lib%ds-test%src%DSTest`(.KList),`method_DSTest_S2KISZUndTEST_`(.KList))=>`#abiCallData(_,_)_EVM-ABI_Bytes_String_TypedArgs`(#token("\"IS_TEST\"","String"),`.List{"_,__EVM-ABI_TypedArgs_TypedArg_TypedArgs"}_TypedArgs`(.KList)) requires #token("true","Bool") ensures #token("true","Bool") [UNIQUE_ID(caed08517e7e2e670fb1c57b79be8c42d076b6a457dd0bd6d81fd3fea5c3c88b), org.kframework.attributes.Location(Location(4477,11,4477,138)), org.kframework.attributes.Source(Source(/Users/secoalba/Documents/PROGRAMACIÓN/BLOCKCHAIN_DEV/SOLIDITY/SECURITY/TOOLS/FORMAL_VERIFICATION/KONTROL/kontrolexample/out/kompiled/contracts.k)), org.kframework.definition.Production(syntax #RuleContent ::= #RuleBody [klabel(#ruleNoConditions), symbol])]
  axiom{R} \implies{R} (
    \and{R}(
      \top{R}(),
      \and{R} (
          \in{SortS2KlibZModforgeZSubstdZModlibZModdsZSubtestZModsrcZModDSTestContract{}, R} (
            X0:SortS2KlibZModforgeZSubstdZModlibZModdsZSubtestZModsrcZModDSTestContract{},
            Lblcontract'Unds'lib'Perc'forge-std'Perc'lib'Perc'ds-test'Perc'src'Perc'DSTest{}()
          ),\and{R} (
          \in{SortS2KlibZModforgeZSubstdZModlibZModdsZSubtestZModsrcZModDSTestMethod{}, R} (
            X1:SortS2KlibZModforgeZSubstdZModlibZModdsZSubtestZModsrcZModDSTestMethod{},
            Lblmethod'Unds'DSTest'Unds'S2KISZUndTEST'Unds'{}()
          ),
          \top{R} ()
        ))),
    \equals{SortBytes{},R} (
      Lblmethod'Unds'lib'Perc'forge-std'Perc'lib'Perc'ds-test'Perc'src'Perc'DSTest{}(X0:SortS2KlibZModforgeZSubstdZModlibZModdsZSubtestZModsrcZModDSTestContract{},X1:SortS2KlibZModforgeZSubstdZModlibZModdsZSubtestZModsrcZModDSTestMethod{}),
     \and{SortBytes{}} (
       Lbl'Hash'abiCallData'LParUndsCommUndsRParUnds'EVM-ABI'Unds'Bytes'Unds'String'Unds'TypedArgs{}(\dv{SortString{}}("IS_TEST"),Lbl'Stop'List'LBraQuotUndsCommUndsUnds'EVM-ABI'Unds'TypedArgs'Unds'TypedArg'Unds'TypedArgs'QuotRBraUnds'TypedArgs{}()),
        \top{SortBytes{}}())))
  [UNIQUE'Unds'ID{}("caed08517e7e2e670fb1c57b79be8c42d076b6a457dd0bd6d81fd3fea5c3c88b"), org'Stop'kframework'Stop'attributes'Stop'Location{}("Location(4477,11,4477,138)"), org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/Users/secoalba/Documents/PROGRAMACI\xd3N/BLOCKCHAIN_DEV/SOLIDITY/SECURITY/TOOLS/FORMAL_VERIFICATION/KONTROL/kontrolexample/out/kompiled/contracts.k)"), org'Stop'kframework'Stop'definition'Stop'Production{}("syntax #RuleContent ::= #RuleBody [klabel(#ruleNoConditions), symbol]")]

```

<img width="1105" alt="image" src="https://github.com/runtimeverification/kontrol/assets/94926493/6c3eea0e-9457-4709-a570-c80794372848">

####  Thank you very much

**Comment by scab24** [comment]
## definition.kore

- https://github.com/scab24/KontrolExample/blob/main/out/kompiled/llvm-library/definition.kore

**Comment by dwightguth** [comment]
Strange. That line is a comment; not sure why it wouldn't get discarded by the tokenizer.

**Comment by Baltoli** [comment]
@scab24 The issue here is that you have a unicode character in the path `/Users/secoalba/Documents/PROGRAMACIÓN/...`, which breaks an internal component of K. Supporting unicode like this is an open feature that we're currently working on, but for now you can work around the issue by renaming the folder that your code lives under to use only ASCII characters.

Sorry for the inconvenience, and please let us know if there's anything else we can do for you!

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/llvm-backend/issues/948 tracks the fix we'll make in the backend.

**Comment by scab24** [comment]
Thank you very much for all your help; thanks to you, I've managed to get everything working perfectly.

As you correctly pointed out, the issue was with ASCII characters ("PROGRAMACIÓN"). I've changed it to ("PROGRAMACION"), and it's working correctly now.

I want to thank you once again for all your time and assistance. Thank you very much!!

- Kontrol build 
<img width="791" alt="image" src="https://github.com/runtimeverification/kontrol/assets/94926493/a2dea7c5-37a3-43cd-8d15-07ce06d6640f">

- kontrol prove --match-test CounterTest.testSetNumber
<img width="875" alt="image" src="https://github.com/runtimeverification/kontrol/assets/94926493/68e619c0-6705-426e-b5bd-16759a761bc7">


- kontrol view-kcfg CounterTest.testSetNumber
<img width="871" alt="image" src="https://github.com/runtimeverification/kontrol/assets/94926493/0158c308-cba2-4017-9b2e-961846c154ca">

**Comment by Baltoli** [comment]
Great, glad to hear it @scab24!
