### ISSUE TITLE
`kontrol view-kcfg` command is not working  

### ISSUE THREAD

**Issue by lisandrasilva** [runtimeverification/kontrol#324]
With the latest version of Kontrol (0.1.34), the `view-kcfg` command is not working although the proof is in the proofs directory. 

**Steps to reproduce**
- Clone this [repo](https://github.com/runtimeverification/_audits_Ethereum-optimism_pausability/tree/develop)
- Go to `packages/contracts-bedrock`
- From that folder, to reproduce the proofs, run the following (further documentation in `test/kontrol`): 
  - `./test/kontrol/scripts/make-summary-deployment` creates necessary files to run the proofs
  - `./test/kontrol/scripts/run-kontrol dev` runs the proofs in dev mode
- To run `kontrol` commands prepend them with `FOUNDRY_PROFILE=kprove`.
- Run `FOUNDRY_PROFILE=kprove kontrol list` and all the proofs are displayed:
```
APRProof: test%kontrol%proofs%L1CrossDomainMessengerKontrol.prove_relayMessage_paused(uint256,address,address,uint256,uint256):0
    status: ProofStatus.PASSED
    admitted: False
    nodes: 15
    pending: 0
    failing: 0
    vacuous: 0
    stuck: 0
    terminal: 2
    refuted: 0
Subproofs: 0

APRProof: test%kontrol%proofs%L1ERC721BridgeKontrol.prove_finalizeBridgeERC21_paused(address,address,address,address,uint256):0
    status: ProofStatus.FAILED
    admitted: False
    nodes: 21
    pending: 0
    failing: 1
    vacuous: 0
    stuck: 0
    terminal: 2
    refuted: 0
Subproofs: 0

APRProof: test%kontrol%proofs%L1StandardBridgeKontrol.prove_finalizeBridgeERC20_paused(address,address,address,address,uint256):0
    status: ProofStatus.FAILED
    admitted: False
    nodes: 25
    pending: 0
    failing: 1
    vacuous: 0
    stuck: 0
    terminal: 2
    refuted: 0
Subproofs: 0

APRProof: test%kontrol%proofs%L1StandardBridgeKontrol.prove_finalizeBridgeETH_paused(address,address,uint256):0
    status: ProofStatus.FAILED
    admitted: False
    nodes: 25
    pending: 0
    failing: 1
    vacuous: 0
    stuck: 0
    terminal: 2
    refuted: 0
Subproofs: 0

APRProof: test%kontrol%proofs%OptimismPortalKontrol.prove_finalizeWithdrawalTransaction_paused(uint256,address,address,uint256,uint256):0
    status: ProofStatus.PASSED
    admitted: False
    nodes: 16
    pending: 0
    failing: 0
    vacuous: 0
    stuck: 0
    terminal: 2
    refuted: 0
Subproofs: 0
```
- However, if we try to inspect the kcfg of one of the proofs, we get that there are no proofs matching:

```bash
contracts-bedrock $ FOUNDRY_PROFILE=kprove kontrol view-kcfg L1StandardBridgeKontrol.prove_finalizeBridgeETH_paused
Traceback (most recent call last):
  File "/nix/store/jk6r4mlqijddxfkr292fas0frfcgkzw3-python3.10-kontrol-0.1.134/bin/.kontrol-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/jk6r4mlqijddxfkr292fas0frfcgkzw3-python3.10-kontrol-0.1.134/lib/python3.10/site-packages/kontrol/__main__.py", line 90, in main
    execute(**vars(args))
  File "/nix/store/jk6r4mlqijddxfkr292fas0frfcgkzw3-python3.10-kontrol-0.1.134/lib/python3.10/site-packages/kontrol/__main__.py", line 369, in exec_view_kcfg
    test_id = foundry.get_test_id(test, version)
  File "/nix/store/jk6r4mlqijddxfkr292fas0frfcgkzw3-python3.10-kontrol-0.1.134/lib/python3.10/site-packages/kontrol/foundry.py", line 309, in get_test_id
    raise ValueError(f'Found no matching proofs for {test}:{version}.')
ValueError: Found no matching proofs for L1StandardBridgeKontrol.prove_finalizeBridgeETH_paused:None.
```

**Comment by anvacaru** [comment]
This needs further investigations. `view-kcfg` seems to work as expected for proofs outside the `optimism` repo.
