### ISSUE TITLE
`kontrol show` crashes if more than one test match the prefix

### ISSUE THREAD

**Issue by lucasmt** [runtimeverification/kontrol#363]
If `kontrol show` is called with a prefix that matches more than one test, it crashes with `ValueError: Expected a single element, found more`. For example, if there are two tests, one called `StartPrankTestSymbolic.testSymbolicPrank` and another called `StartPrankTestSymbolic.testSymbolicPrankSplit`, calling `kontrol show StartPrankTestSymbolic.testSymbolicPrank` produces the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lucasmt/kontrol/refute-node/src/kontrol/__main__.py", line 90, in main
    execute(**vars(args))
  File "/home/lucasmt/kontrol/refute-node/src/kontrol/__main__.py", line 336, in exec_show
    output = foundry_show(
  File "/home/lucasmt/kontrol/refute-node/src/kontrol/foundry.py", line 522, in foundry_show
    contract_name, _ = single(foundry.matching_tests([test])).split('.')
  File "/home/lucasmt/pyk/refute-node/src/pyk/utils.py", line 272, in single
    raise ValueError('Expected a single element, found more', fst, snd)
ValueError: ('Expected a single element, found more', 'test%StartPrankTestSymbolic.testSymbolicPrankSplit(address)', 'test%StartPrankTestSymbolic.testSymbolicPrank(address)')
```
Note that `kontrol show StartPrankTestSymbolic.testSymbolicPrankSplit` can be called with no problem, but there is no way to display the KCFG for `StartPrankTestSymbolic.testSymbolicPrank`, since its name is a strict prefix of the other test.

Some alternatives on how to handle this:
* Require the argument to `kontrol show` to be the full name of the test, not just a prefix.
* Keep the current behavior by default, but add an option (e.g. `--full-name`) to match the full name instead. Rewrite the error message above to suggest this as an option to the user.
* Print the KCFGs for all tests that match the prefix (might be hard to read and confusing if the KCFGs are large).

**Comment by palinatolmach** [comment]
Thanks @lucasmt! I also ran into a related issue today, and it seems that there's a mismatch between loading proof data for `kontrol show` and `kontrol view-kcfg`.

If the contract contains tests with the same prefix, e.g. `test_complex_type` and `test_complex_type_array`, and only `test_complex_type_array` (the longer one) has been executed, 
```
kontrol view-kcfg CDTest.test_complex_type
```
will show the KCFG for `test_complex_type_array` (since it matches the prefix and is present in `out/proofs`), although it might be misleading for the user. 

On the other hand, as you've said,
```
kontrol show CDTest.test_complex_type
```
crashes with 
```
ValueError: ('Expected a single element, found more', 'test%CDTest.test_complex_type_array((uint256,bytes)[])', 'test%CDTest.test_complex_type((uint256,bytes),bytes[],uint256)')
```.

**Comment by palinatolmach** [comment]
The error message thrown if multiple proofs with the same name are encountered was improved in https://github.com/runtimeverification/kontrol/pull/394, but I'm not sure if is solved the discrepancy described above — will need to re-test.
