### ISSUE TITLE
Kontrol crashes upon reaching ECDSA.Recover

### ISSUE THREAD

**Issue by ACassimiro** [runtimeverification/kontrol#380]
While debugging the WETH contract, I noticed that Kontrol would crash when attempting to prove the `withdrawal` function. Upon digging further into the reason for the failure, I've created a simplified, minimal version of the test that is failing to be proved, and placed it in [ECDSA_Test branch](https://github.com/runtimeverification/kontrol/tree/ecdsa_test). The crash log is as follows:

```
[Warn] Assertion failed
CallStack (from HasCallStack):
  assert, called at src/Kore/Builtin/Krypto.hs:308:5 in kore-0.60.0.0-AilWsOSAUb2IUrLwjjn1oR:Kore.Builtin.Krypto
ERROR 2024-02-07 11:03:50,562 kevm_pyk.utils - Proof crashed: src%ECDSARecover_Test.trigger_ECDSARecover(uint256):0
Runtime error
Traceback (most recent call last):
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kore/rpc.py", line 808, in _request
    return self._client.request(method, **params)
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kore/rpc.py", line 247, in request
    return self._default_client.request(method, **params)
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kore/rpc.py", line 326, in request
    self._check(data)
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kore/rpc.py", line 338, in _check
    raise JsonRpcError(**response['error'])
pyk.kore.rpc.JsonRpcError: Runtime error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/nix/store/nx08py50nggxs03bzv05cf34lb829drl-python3.10-kevm-pyk-1.0.418/lib/python3.10/site-packages/kevm_pyk/utils.py", line 117, in run_prover
    prover.advance_proof(
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/proof/reachability.py", line 773, in advance_proof
    self.advance_pending_node(
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/proof/reachability.py", line 1043, in advance_pending_node
    super().advance_pending_node(
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/proof/reachability.py", line 737, in advance_pending_node
    self.kcfg_explore.extend(
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 372, in extend
    extend_result = self.extend_cterm(
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 415, in extend_cterm
    cterm, next_cterms, depth, vacuous, next_node_logs = self.cterm_execute(
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 92, in cterm_execute
    response = self._kore_client.execute(
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kore/rpc.py", line 856, in execute
    result = self._request('execute', **params)
  File "/nix/store/ap9c65dgpl2lfyfci44c5ddpvvbpwgff-python3.10-pyk-0.1.572/lib/python3.10/site-packages/pyk/kore/rpc.py", line 811, in _request
    raise KoreClientError(message=err.message, code=err.code, data=err.data) from err
pyk.kore.rpc.KoreClientError: Runtime error
[Info#proxy] Server shutting down
PROOF FAILED: src%ECDSARecover_Test.trigger_ECDSARecover(uint256):0
```

Previously to being brought here, this issue was also [discussed with the Haskell backend team](https://github.com/runtimeverification/hs-backend-booster/issues/491).

While I understand that Kontrol may fail to generate proof in such a scenario, I don't think that the tool should crash.

KEVM Claims generated by the minimal example: [kevm-claims (1).txt](https://github.com/runtimeverification/kontrol/files/14350882/kevm-claims.1.txt)

**Comment by palinatolmach** [comment]
We ran some debugging with @anvacaru, and identified the potential root cause of the issue, which is the branching on symbolic `CALLER_ID` (i.e., `msg.sender`) address potentially being a precompiled address (which is not possible). In this case, `#precompiled(X)` is called on a symbolic value, while we're only computing it if `X` is in `{0..9}`.

The two possible ways to fix it are:
- to label rules for `isPrecompiled` with `[concrete]` and `[symbolic]` tags so that it evaluates to false if `X` is symbolic (we should carefully consider the consequences of adding these and the necessary `simplification` tags):
```
https://runtimeverification.slack.com/archives/D05FXFMC2AZ/p1708674344850159
rule [isPrecompiledAccount.true]:  #isPrecompiledAccount(ACCTCODE, SCHED) => true  requires         ACCTCODE in #precompiledAccounts(SCHED) [concrete(ACCTCODE, SCHED)]
rule [isPrecompiledAccount.false]: #isPrecompiledAccount(ACCTCODE, SCHED) => false requires notBool ACCTCODE in #precompiledAccounts(SCHED) [concrete(ACCTCODE, SCHED)]
rule [isPrecompiledAccount.symbolic]: #isPrecompiledAccount(ACCT, _) => false                                                     [symbolic(ACCT), simplification]
```
- add a constraint assuming that `CALLER_ID` is not a precompiled contract in Kontrol, similar to 
```
_account_constraints.append(
  mlEqualsFalse(KEVM.is_precompiled_account(acct_id.args[0], cterm.cell('SCHEDULE_CELL')))
)
```

**Comment by palinatolmach** [comment]
Further debugging and fixing of this issue is blocked by the fast that one of the Kontrol changes in the past 2-3 weeks introduced spurious branching to the test execution:
```
┣━━┓ constraint: { false #Equals ( false andBool #changesState ( CALL , ( chop ( ( 2300 *Int bool2Word ( VV0_wad_114b9705:Int ==Int 0 ) ) ) : ( CALLER_ID:Int : ( VV0_wad_114b9705:Int : ( 128 : ( 0 : ( 128 : ( 0 : ( 128 : ( VV0_wad_114b9705:Int : ( chop ( ( 2300 *Int bool2Word ( VV0_wad_114b9705:Int ==Int 0 ) ) ) : ( CALLER_ID:Int : ( VV0_wad_114b9705:Int : ( 271 : ( selector ( "testECDSARecover(uint256)" ) : .WordStack ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) }
┃  │
┃  ├─ 4 (split)
┃  │   k: #next [ CALL ] ~> #execute ~> CONTINUATION:K
┃  │   pc: 1011
┃  │   callDepth: 0
┃  │   statusCode: STATUSCODE:StatusCode
┃  │   src: lib/forge-std/src/StdInvariant.sol:84:85
┃  ┃
┃  ┃ (branch)
┃  ┣━━┓ constraint: { false #Equals ( false andBool #changesState ( CALL , ( chop ( ( 2300 *Int bool2Word ( VV0_wad_114b9705:Int ==Int 0 ) ) ) : ( CALLER_ID:Int : ( VV0_wad_114b9705:Int : ( 128 : ( 0 : ( 128 : ( 0 : ( 128 : ( VV0_wad_114b9705:Int : ( chop ( ( 2300 *Int bool2Word ( VV0_wad_114b9705:Int ==Int 0 ) ) ) : ( CALLER_ID:Int : ( VV0_wad_114b9705:Int : ( 271 : ( selector ( "testECDSARecover(uint256)" ) : .WordStack ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) }
┃  ┃  │
┃  ┃  ├─ 6 (split)
┃  ┃  │   k: #next [ CALL ] ~> #execute ~> CONTINUATION:K
┃  ┃  │   pc: 1011
┃  ┃  │   callDepth: 0
┃  ┃  │   statusCode: STATUSCODE:StatusCode
┃  ┃  │   src: lib/forge-std/src/StdInvariant.sol:84:85
┃  ┃  ┃
┃  ┃  ┃ (branch)
┃  ┃  ┣━━┓ constraint: { false #Equals ( false andBool #changesState ( CALL , ( chop ( ( 2300 *Int bool2Word ( VV0_wad_114b9705:Int ==Int 0 ) ) ) : ( CALLER_ID:Int : ( VV0_wad_114b9705:Int : ( 128 : ( 0 : ( 128 : ( 0 : ( 128 : ( VV0_wad_114b9705:Int : ( chop ( ( 2300 *Int bool2Word ( VV0_wad_114b9705:Int ==Int 0 ) ) ) : ( CALLER_ID:Int : ( VV0_wad_114b9705:Int : ( 271 : ( selector ( "testECDSARecover(uint256)" ) : .WordStack ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) }
┃  ┃  ┃  │
┃  ┃  ┃  ├─ 8 (split)
┃  ┃  ┃  │   k: #next [ CALL ] ~> #execute ~> CONTINUATION:K
┃  ┃  ┃  │   pc: 1011
┃  ┃  ┃  │   callDepth: 0
┃  ┃  ┃  │   statusCode: STATUSCODE:StatusCode
┃  ┃  ┃  │   src: lib/forge-std/src/StdInvariant.sol:84:85
┃  ┃  ┃  ┃
```
I'm currently trying to isolate the version where this behavior was introduced.

**Comment by palinatolmach** [comment]
I don't have any explanation for that yet, but it seems that this branching starts to occur in the `mockCall` PR in Kontrol: https://github.com/runtimeverification/kontrol/pull/318/files.

**Comment by PetarMax** [comment]
The solution to this problem, I believe, is to add constraints that say that the relevant contract address is not a precompiled account address. Something similar has been done in [this PR](https://github.com/runtimeverification/evm-semantics/pull/2317).

**Comment by palinatolmach** [comment]
Yes, it seems so, thank you @PetarMax! It's possible that this [PR](https://github.com/runtimeverification/evm-semantics/pull/2317) already fixed the issue  — the address in question was `CALLER_ID`, which was constrained. I'll give it a try today!

**Comment by palinatolmach** [comment]
I just ran the test @ACassimiro provided
```
pragma solidity =0.8.13;

import "forge-std/Test.sol";

contract ECDSARecoverTest is Test {
    function testECDSARecover(uint256 wad) public {
        payable(msg.sender).transfer(wad);
    }
}
```
with the latest Kontrol version (0.1.187), and I don't see any of the above issues anymore: there's no spurious branching and no crashes on the `#isPrecompiledAccount` check (so it got fixed by https://github.com/runtimeverification/evm-semantics/pull/2317). 

At the same time, it fails in a minute (with `--fail-fast`) with the KCFG I posted below. `#checkBalanceUnderflow` looks normal to me, considering how unconstrained the transfer in the test is, but I don't think `#call_foundry 0 b""` is supposed to happen — I suppose it's an indicator that another constraint on `CALLER_ID` we should add is that it's not the Foundry cheatcode address.

```
┌─ 1 (root, init)
│   k: #execute ~> CONTINUATION:K
│   pc: 0
│   callDepth: 0
│   statusCode: STATUSCODE:StatusCode
│   src: test/ECDSATest.sol:4:9
│
│  (406 steps)
├─ 3
│   k: #next [ CALL ] ~> #execute ~> CONTINUATION:K
│   pc: 657
│   callDepth: 0
│   statusCode: STATUSCODE:StatusCode
│   src: lib/forge-std/src/StdInvariant.sol:76:79
┃
┃ (1 step)
┣━━┓
┃  │
┃  ├─ 4
┃  │   k: #addr [ CALL ] ~> #exec [ CALL ] ~> #pc [ CALL ] ~> #execute ~> CONTINUATION:K
┃  │   pc: 657
┃  │   callDepth: 0
┃  │   statusCode: STATUSCODE:StatusCode
┃  │   src: lib/forge-std/src/StdInvariant.sol:76:79
┃  │
┃  │  (5 steps)
┃  ├─ 6
┃  │   k: #checkCall 728815563385977040452943777879061427756277306518 VV0_wad_114b9705:Int ...
┃  │   pc: 657
┃  │   callDepth: 0
┃  │   statusCode: STATUSCODE:StatusCode
┃  │   src: lib/forge-std/src/StdInvariant.sol:76:79
┃  ┃
┃  ┃ (1 step)
┃  ┣━━┓
┃  ┃  │
┃  ┃  ├─ 7
┃  ┃  │   k: #call_foundry 0 b"" ~> #return_foundry 128 0 ~> #pc [ CALL ] ~> #execute ~> CONT ...
┃  ┃  │   pc: 657
┃  ┃  │   callDepth: 0
┃  ┃  │   statusCode: STATUSCODE:StatusCode
┃  ┃  │   src: lib/forge-std/src/StdInvariant.sol:76:79
┃  ┃  │
┃  ┃  │  (1 step)
┃  ┃  └─ 9 (stuck, leaf)
┃  ┃      k: #error_foundry 0 b"" ~> #return_foundry 128 0 ~> #pc [ CALL ] ~> #execute ~> CON ...
┃  ┃      pc: 657
┃  ┃      callDepth: 0
┃  ┃      statusCode: FOUNDRY_UNIMPLEMENTED
┃  ┃      src: lib/forge-std/src/StdInvariant.sol:76:79
┃  ┃
┃  ┗━━┓
┃     │
┃     ├─ 8 (split)
┃     │   k: #checkBalanceUnderflow 728815563385977040452943777879061427756277306518 VV0_wad_ ...
┃     │   pc: 657
┃     │   callDepth: 0
┃     │   statusCode: STATUSCODE:StatusCode
┃     │   src: lib/forge-std/src/StdInvariant.sol:76:79
┃     ┃
┃     ┃ (branch)
┃     ┣━━┓ constraint: { true #Equals 0 <Int VV0_wad_114b9705:Int }
┃     ┃  │
┃     ┃  └─ 10 (leaf, pending)
┃     ┃      k: #checkBalanceUnderflow 728815563385977040452943777879061427756277306518 VV0_wad_ ...
┃     ┃      pc: 657
┃     ┃      callDepth: 0
┃     ┃      statusCode: STATUSCODE:StatusCode
┃     ┃      src: lib/forge-std/src/StdInvariant.sol:76:79
┃     ┃
┃     ┗━━┓ constraint: { true #Equals VV0_wad_114b9705:Int <=Int 0 }
┃        │
┃        └─ 11 (leaf, pending)
┃            k: #checkBalanceUnderflow 728815563385977040452943777879061427756277306518 VV0_wad_ ...
┃            pc: 657
┃            callDepth: 0
┃            statusCode: STATUSCODE:StatusCode
┃            src: lib/forge-std/src/StdInvariant.sol:76:79
┃
┗━━┓
   │
   └─ 5 (vacuous, leaf)
       k: #next [ CALL ] ~> #execute ~> CONTINUATION:K
       pc: 657
       callDepth: 0
       statusCode: STATUSCODE:StatusCode
       src: lib/forge-std/src/StdInvariant.sol:76:79


┌─ 2 (root, leaf, target, terminal)
│   k: #halt ~> CONTINUATION:K
│   pc: PC_CELL_5d410f2a:Int
│   callDepth: CALLDEPTH_CELL_5d410f2a:Int
│   statusCode: STATUSCODE_FINAL:StatusCode
```

**Comment by palinatolmach** [comment]
A call to Foundry cheatcode contract (`645326474426547203313410069153905908525362434349`) can be avoided using the [`notBuiltinAddress(address)`](https://github.com/runtimeverification/kontrol-cheatcodes/blob/2c48ae1ab44228c199dca29414c0b4b18a3434e6/src/KontrolCheats.sol#L40C14-L40C31) function that is shipped with KontrolCheats contract:
```
contract ECDSARecoverTest is Test, KontrolCheats {
    function testECDSARecover(uint256 wad) public {
        vm.assume(notBuiltinAddress(msg.sender));
        payable(msg.sender).transfer(wad);
    }
}
```

In this case, though, the branching still occurs, but only negative branch gets executed (KCFG below). @ACassimiro @anvacaru do you think we can consider this issue closed? 

```
┌─ 1 (root, init)
│   k: #execute ~> CONTINUATION:K
│   pc: 0
│   callDepth: 0
│   statusCode: STATUSCODE:StatusCode
│   src: test/ECDSATest.sol:5:11
│
│  (427 steps)
├─ 3 (split)
│   k: JUMPI 2230 bool2Word ( 645326474426547203313410069153905908525362434349 ==Int CA ...
│   pc: 2195
│   callDepth: 0
│   statusCode: STATUSCODE:StatusCode
┃
┃ (branch)
┣━━┓ constraint: { true #Equals 645326474426547203313410069153905908525362434349 ==Int CALLER_ID:Int }
┃  │
┃  ├─ 4
┃  │   k: JUMPI 2230 bool2Word ( 645326474426547203313410069153905908525362434349 ==Int CA ...
┃  │   pc: 2195
┃  │   callDepth: 0
┃  │   statusCode: STATUSCODE:StatusCode
┃  │
┃  │  (357 steps)
┃  └─ 6 (vacuous, leaf)
┃      k: #next [ CALL ] ~> #execute ~> CONTINUATION:K
┃      pc: 846
┃      callDepth: 0
┃      statusCode: STATUSCODE:StatusCode
┃      src: lib/forge-std/src/StdInvariant.sol:73:74
┃
┗━━┓ constraint: { true #Equals ( notBool 645326474426547203313410069153905908525362434349 ==Int CALLER_ID:Int ) }
   │
   ├─ 5
   │   k: JUMPI 2230 bool2Word ( 645326474426547203313410069153905908525362434349 ==Int CA ...
   │   pc: 2195
   │   callDepth: 0
   │   statusCode: STATUSCODE:StatusCode
   │
   │  (400 steps)
   ├─ 7
   │   k: #next [ CALL ] ~> #execute ~> CONTINUATION:K
   │   pc: 846
   │   callDepth: 0
   │   statusCode: STATUSCODE:StatusCode
   │   src: lib/forge-std/src/StdInvariant.sol:73:74
   ...
```

**Comment by palinatolmach** [comment]
The constraint on the address not being Foundry cheatcode's address will be added by @PetarMax in https://github.com/runtimeverification/kontrol/pull/355, which will close this issue. In the meantime, the `vm.assume(...)` workaround can be used to avoid reverting on a call to the cheatcode contract.

**Comment by palinatolmach** [comment]
The above issue should get fixed by https://github.com/runtimeverification/kontrol/pull/427.

**Comment by ACassimiro** [comment]
Thank you, @palinatolmach!
