### ISSUE TITLE
"Local variable 'regen' referenced before assignment" error in `kontrol build`

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#513]
I think an issue got introduced in https://github.com/runtimeverification/kontrol/pull/501. When running 
```
❯ kontrol build --require lemmas/eq-lemmas.k --module-import EquivalenceTest:EQUIVALENCE-LEMMAS
```
in https://github.com/runtimeverification/secureum-kontrol after running the same command before and w/o any code changes (i.e., I'm expecting this command to finish successfully within a few seconds), I'm getting
```
Traceback (most recent call last):
  File "/nix/store/96maqav2llhlhxxs21qhddzp1wcjq27r-python3.10-kontrol-0.1.246/bin/.kontrol-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/96maqav2llhlhxxs21qhddzp1wcjq27r-python3.10-kontrol-0.1.246/lib/python3.10/site-packages/kontrol/__main__.py", line 142, in main
    execute(options)
  File "/nix/store/96maqav2llhlhxxs21qhddzp1wcjq27r-python3.10-kontrol-0.1.246/lib/python3.10/site-packages/kontrol/__main__.py", line 202, in exec_build
    foundry_kompile(
  File "/nix/store/96maqav2llhlhxxs21qhddzp1wcjq27r-python3.10-kontrol-0.1.246/lib/python3.10/site-packages/kontrol/kompile.py", line 78, in foundry_kompile
    if regen or not req_path.exists():
UnboundLocalError: local variable 'regen' referenced before assignment
```
@nwatson22 can you please take a look?

**Comment by nwatson22** [comment]
I've reproduced this and fixed it in #514. The `regen` variable in `foundry_kompile` was previously referring to a function parameter which was removed.
