### ISSUE TITLE
Give useful error information when working with a test with several matching IDs

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/kontrol#69]
When calling `foundry-view-kcfg` and there are several versions of the same proof, a Python error gets propagated to the top.

It would be a lot nicer if we printed a helpful error message, and listed the available IDs (maybe even with the last time it was run, or some other useful data that can help the user understand which is which).

Data that could be useful to list for each ID:

- When was the proof first ran?
- What's the status of the proof?
- Is the test up to date with the current version of the test or is it outdated?
- What's the type of the test (e.g. its inputs)

```
Traceback (most recent call last):
  File "/nix/store/mhinp1n2lx3bxr0c6iq6f4zh490nw16n-python3.10-kevm-pyk-1.0.301/bin/.kontrolx-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/mhinp1n2lx3bxr0c6iq6f4zh490nw16n-python3.10-kevm-pyk-1.0.301/lib/python3.10/site-packages/kontrolx/__main__.py", line 68, in main
    execute(**vars(args))
  File "/nix/store/mhinp1n2lx3bxr0c6iq6f4zh490nw16n-python3.10-kevm-pyk-1.0.301/lib/python3.10/site-packages/kontrolx/__main__.py", line 261, in exec_foundry_view_kcfg
    test_id = foundry.get_test_id(test, version)
  File "/nix/store/mhinp1n2lx3bxr0c6iq6f4zh490nw16n-python3.10-kevm-pyk-1.0.301/lib/python3.10/site-packages/kontrolx/foundry.py", line 308, in get_test_id
    raise ValueError(
ValueError: Found 3 matching proofs for PinataTest.testA0(uint256,bool). Use the --version flag to choose one.
```

**Comment by hjorthjort** [comment]
Closing in favor of https://github.com/runtimeverification/kontrol/issues/30
